-- MySQL Script generated by MySQL Workbench
-- 06/10/16 10:30:06
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema bd_terraplanagem
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bd_terraplanagem
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd_terraplanagem` DEFAULT CHARACTER SET utf8 ;
USE `bd_terraplanagem` ;

-- -----------------------------------------------------
-- Table `bd_terraplanagem`.`fornecedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_terraplanagem`.`fornecedor` (
  `codfor` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'Código do Fornecedor do Material.',
  `nomfor` VARCHAR(60) NOT NULL COMMENT 'Nome do Fornecedor do Material.',
  PRIMARY KEY (`codfor`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd_terraplanagem`.`material`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_terraplanagem`.`material` (
  `codmat` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'Código do Material',
  `desmat` VARCHAR(60) NOT NULL COMMENT 'Descrição do Material(Barro, Piçarra, Brita, Areia, etc.).',
  `premat` DECIMAL(8,2) NOT NULL COMMENT 'Preço Basico do Material.',
  `unimat` VARCHAR(20) NOT NULL COMMENT 'Unidade de medida do Material.',
  PRIMARY KEY (`codmat`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd_terraplanagem`.`motorista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_terraplanagem`.`motorista` (
  `codmot` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'Código do Motorista.\n',
  `nommot` VARCHAR(60) NOT NULL COMMENT 'Nome completo do Motorista.',
  PRIMARY KEY (`codmot`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd_terraplanagem`.`local`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_terraplanagem`.`local` (
  `codloc` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'Código da Obra.',
  `nomloc` VARCHAR(60) NOT NULL COMMENT 'Nome da Obra.',
  PRIMARY KEY (`codloc`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd_terraplanagem`.`rota`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_terraplanagem`.`rota` (
  `codrot` INT NOT NULL AUTO_INCREMENT COMMENT 'Código da Rota da Viagem.',
  `dmtrot` DECIMAL(8,2) NOT NULL COMMENT 'Distância em Metros da Rota da Viagem',
  `local_codloc` INT(11) NOT NULL,
  `local_codloc1` INT(11) NOT NULL,
  PRIMARY KEY (`codrot`),
  INDEX `fk_rota_local1_idx` (`local_codloc` ASC),
  INDEX `fk_rota_local2_idx` (`local_codloc1` ASC),
  CONSTRAINT `fk_rota_local1`
    FOREIGN KEY (`local_codloc`)
    REFERENCES `bd_terraplanagem`.`local` (`codloc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rota_local2`
    FOREIGN KEY (`local_codloc1`)
    REFERENCES `bd_terraplanagem`.`local` (`codloc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd_terraplanagem`.`tipoveiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_terraplanagem`.`tipoveiculo` (
  `codtipo` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'Codigo do Tipo de Veículo.',
  `destipo` VARCHAR(60) NOT NULL COMMENT 'Tipo do veiculo, Exemplo: Trucada, Toco, Carreta, etc.',
  PRIMARY KEY (`codtipo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd_terraplanagem`.`veiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_terraplanagem`.`veiculo` (
  `codvei` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'Código do Veículo.',
  `plavei` VARCHAR(8) NOT NULL COMMENT 'Placa do Veículo.',
  `capvei` DECIMAL(6,2) NOT NULL COMMENT 'Capacidade de Carga do Veículo em metros cúbicos.',
  `codtipo` INT(11) NOT NULL,
  `codmot` INT(11) NOT NULL,
  PRIMARY KEY (`codvei`),
  INDEX `fk_Veiculo_TipoVeiculo1_idx` (`codtipo` ASC),
  INDEX `fk_Veiculo_Motorista1_idx` (`codmot` ASC),
  CONSTRAINT `fk_Veiculo_Motorista1`
    FOREIGN KEY (`codmot`)
    REFERENCES `bd_terraplanagem`.`motorista` (`codmot`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Veiculo_TipoVeiculo1`
    FOREIGN KEY (`codtipo`)
    REFERENCES `bd_terraplanagem`.`tipoveiculo` (`codtipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd_terraplanagem`.`viagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_terraplanagem`.`viagem` (
  `codvia` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'Código da Viagem.',
  `datvia` DATE NOT NULL COMMENT 'Data da Viagem',
  `quavia` DECIMAL(8,2) NOT NULL COMMENT 'Quantidade em Metros cúbicos de Material da Viagem.',
  `previa` DECIMAL(8,2) NULL DEFAULT NULL COMMENT 'Preço da Viagem por Metros Rodados.',
  `codmat` INT(11) NOT NULL,
  `codvei` INT(11) NOT NULL,
  `codmot` INT(11) NOT NULL,
  `codfor` INT(11) NOT NULL,
  `codrot` INT NOT NULL,
  PRIMARY KEY (`codvia`),
  INDEX `fk_Viagem_Material1_idx` (`codmat` ASC),
  INDEX `fk_Viagem_Veiculo1_idx` (`codvei` ASC),
  INDEX `fk_Viagem_Motorista1_idx` (`codmot` ASC),
  INDEX `fk_Viagem_Fornecedor1_idx` (`codfor` ASC),
  INDEX `fk_Viagem_Rota1_idx` (`codrot` ASC),
  CONSTRAINT `fk_Viagem_Fornecedor1`
    FOREIGN KEY (`codfor`)
    REFERENCES `bd_terraplanagem`.`fornecedor` (`codfor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Viagem_Material1`
    FOREIGN KEY (`codmat`)
    REFERENCES `bd_terraplanagem`.`material` (`codmat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Viagem_Motorista1`
    FOREIGN KEY (`codmot`)
    REFERENCES `bd_terraplanagem`.`motorista` (`codmot`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Viagem_Rota1`
    FOREIGN KEY (`codrot`)
    REFERENCES `bd_terraplanagem`.`rota` (`codrot`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Viagem_Veiculo1`
    FOREIGN KEY (`codvei`)
    REFERENCES `bd_terraplanagem`.`veiculo` (`codvei`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
